default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>

development:
  <<: *default
  host: localhost
  database: rails_api_psql_development

test:
  <<: *default
  host: localhost
  database: rails_api_psql_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
